### ISSUE TITLE
excel-to-markdown-table not work with Excel 2016 

### ISSUE THREAD

**Issue by FrankSagt** [csholmq/vscode-excel-to-markdown-table#12]
with VS-Code and the add-in "excel-to-markdown-table" works only with Excel 2013. 

The new Excel version 2016 does not work. 

Will there be another update?

thanks
Frank

**Comment by csholmq** [comment]
I don't have access to Excel 2016 I'm afraid. So I am a bit dead in the water here.

**Comment by Markus-Hanisch** [comment]
@FrankSagt  
Generally speaking, I cannot confirm that behavior. Make sure to use `Shift+Alt+V` (as described in the [extension's documentation](https://marketplace.visualstudio.com/items?itemName=csholmq.excel-to-markdown-table&ssr=false#overview) instead of `Ctrl+V` to paste the Excel table or table data range into the .md file in VS Code. However, I found an issue with left aligned headers while testing.

I tested with Microsoft Excel 2016 (16.0.4966.1000) MSO (16.0.4939.1000) 32-bit
Excel editing language: en-US
Excel display language: de-DE

**Test cases:**
1. Excel data range 
*works like a charm*
2. Excel data range formatted as table (`Ctrl+T` in Excel)
*works like a charm*
3. Excel table with hidden column (only unhidden columns get copied to VS Code)
*works like a charm*
4. Excel table with applied filter (only filtered rows get copied to VS Code)
*works like a charm*
5. Excel table with left, center and right header alignment (e.g. `rHeaderRight`)
*issue with left aligned header*
Markdown Output: 
```markdown
| Heading1 | Heading2 | Heading3 |
|-----------|:---------:|----------:|
| rooooooooooooooow 1     | rooooooooooooooow 2     | rooooooooooooooow 3      |
```
| Heading1 | Heading2 | Heading3 |
|-----------|:---------:|----------:|
| rooooooooooooooow 1     | rooooooooooooooow 2     | rooooooooooooooow 3      |

@csholmq
Thank you for this awesome extension 👍 
My testing shows that pre-fxing the heading with `^l` results in a centered heading which seems to be the default setting as well. See the markdown above is missing the `:`
Expected markdown output:
```markdown
| Heading1 | Heading2 | Heading3 |
|:----------|:---------:|----------:|
| rooooooooooooooow 1     | rooooooooooooooow 2     | rooooooooooooooow 3      |
```
| Heading1 | Heading2 | Heading3 |
|:----------|:---------:|----------:|
| rooooooooooooooow 1     | rooooooooooooooow 2     | rooooooooooooooow 3      |

**Comment by JulioIzquierdo** [comment]
I'm using Excel 2016 with VS Code 1.44.1.  When using the combo key Shift+Alt+V, all I get is Menu Item View.  Am I doing something wrong here?  
Even when running from the Command Palette, nothing happens.

I'm pretty excited that this extension exist and I'm very anxious to see it working.

Please advise!

I would like to add that the file is a *.md file.

**Comment by JulioIzquierdo** [comment]
I would be interested in give a helping hand here.  I just need some assistance in setting up the dev environment. :-)

**Comment by JulioIzquierdo** [comment]
I've setup my dev environment and now I see the problem.  The first column header was empty and it did not like that.  That caused an exception.  I put a . in the first column header and it worked this time.  This is with Excel 2016.  👍 
Thank you!

**Comment by csholmq** [comment]
@JulioIzquierdo Ah, thanks for the feedback. That is an issue with blank cells.

Does the problem persist if you write something in the cell and then delete it? From what I remember the cell isn't blank anymore then. Just empty.

**Comment by JulioIzquierdo** [comment]
> @JulioIzquierdo Ah, thanks for the feedback. That is an issue with blank cells.
> 
> Does the problem persist if you write something in the cell and then delete it? From what I remember the cell isn't blank anymore then. Just empty.

I just tried deleting that first column header and it did not work however having an empty cell anywhere else works just fine.  I even tried putting in 1 blank space and then a few more blank spaces and it did not work.  Something to do with just the first column header being empty.

**Comment by csholmq** [comment]
Got it. Could you debug the issue and extract a working example vs a non-working example before it's been parsed by the plugin? I.e the `rawData` in the `pasteText` function.

**Comment by JulioIzquierdo** [comment]
> Got it. Could you debug the issue and extract a working example vs a non-working example before it's been parsed by the plugin? I.e the `rawData` in the `pasteText` function.

It may be difficult to see but there is only 1 tab before Header 2 in the non-working example.  See attached pic further below.

**Working Example:**
"Header 1	Header2	Header 3	Header 4	Header 5	Header 6
Data Row 1	data				
Data Row 2		data			
Data Row 3			data		
Data Row 4				data	
Data Row 5					data
"
**Non-Working Example:**
"	Header2	Header 3	Header 4	Header 5	Header 6
Data Row 1	data				
Data Row 2		data			
Data Row 3			data		
Data Row 4				data	
Data Row 5					data
"
![Excel2Markdown Examples](https://user-images.githubusercontent.com/10266031/79629325-1debc900-8106-11ea-8a43-3958afc0eac2.png)

**Comment by csholmq** [comment]
Perfect, thanks! Then we can make a unit test of this and refactor `parseText` to cover it.

Feel free to give it a try. I won't be able to in at least a few days.

**Comment by srlennon** [comment]
Excel for Office 365 MSO (16.0.11929.20760) 64-bit definitely not working.

Input:
![image](https://user-images.githubusercontent.com/6245017/82778818-d50df980-9e95-11ea-924b-5b8f2fb74412.png)

VS Code Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Shift-Alt-V Result:
|  |
|--|

**Comment by shelper** [comment]
i am using ms excel office 365, my verison of excel 
i got nothing when i paste using either shift-alt-v or run from the command 


![image](https://user-images.githubusercontent.com/546163/104376825-8fb93d80-54f3-11eb-81e2-5103842c340c.png)

**Comment by goplayerjuggler** [comment]
It's not working for me either.
Excel 160.0.5110 32-bit
I copied data from Excel. Pasting it into a text editor without using the extension gives this: 
```
a	b
c	d
```
Using the extension, in VS code I get nothing: 
```
|  |
|--|
```

However pasting it into this github comment Window works - it's a workaround! I got the expected values:
```
a | b
-- | --
c | d
```

**Comment by csholmq** [comment]
Just released a new version using the new vscode API. Please test and reopen this issue if it still persists.
